name: CI Pre-Vercel Checks

on:
  push:
    branches:
      - main # 或者您的主要开发分支，例如 develop
  pull_request:
    branches:
      - main # 或者您的主要开发分支

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建议使用与 Vercel 和本地一致的 Node.js 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 使用 npm ci 来确保一致和快速的依赖安装

      - name: Run ESLint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run test 