name: CI Pre-Vercel Checks

on:
  push:
    branches:
      - main # 或者您的主要开发分支，例如 develop
      - F-B  # 前后端联调分支
  pull_request:
    branches:
      - main # 或者您的主要开发分支
      - F-B  # 前后端联调分支

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建议使用与 Vercel 和本地一致的 Node.js 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 使用 npm ci 来确保一致和快速的依赖安装

      - name: Display Git Commit SHA
        run: |
          echo "Current Commit SHA: $(git rev-parse HEAD)"

      - name: Display package.json lint script
        run: |
          echo "Attempting to read lint script from package.json:"
          node -e "try { console.log(JSON.stringify(require('./package.json').scripts.lint)); } catch (e) { console.error('Error reading or parsing lint script:', e.message); process.exit(1); }"
      
      - name: Display .eslintrc.json content
        run: |
          echo "Attempting to read .eslintrc.json:"
          cat .eslintrc.json || echo ".eslintrc.json not found or cat failed"

      - name: Run ESLint
        run: npm run lint

      - name: Run Build
        run: npm run build

      # - name: Run Tests # Step removed
      #   run: npm run test 